version: '3'
services:
  cassandra:
    image: cassandra
    command: bash -c 'if [ -z "$$(ls -A /var/lib/cassandra/)" ] ; then sleep 0; fi && /docker-entrypoint.sh cassandra -f'
    # Network for the nodes to communicate
    networks:
      - network1
    # Maps cassandra data to a local folder. This preserves data across
    # container restarts. Note a folder n1data get created locally
    volumes:
      - ./cassandra/data:/var/lib/cassandra
    # Docker constainer environment variable. We are using the
    # CASSANDRA_CLUSTER_NAME to name the cluster. This needs to be the same
    # across clusters. We are also declaring that DC1N1 is a seed node.
    environment:
        - CASSANDRA_CLUSTER_NAME=dev_cluster
        - CASSANDRA_SEEDS=cassandra
        # Exposing ports for inter cluste communication
    ports:
      - 7000:7000
      - 9042:9042

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    networks:
      - network1
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

networks:
  network1:
    driver: bridge
